### ISSUE TITLE
`tokio-postgres` v0.7.9 breaks `load_config`

### ISSUE THREAD

**Issue by ryzhyk** [3liz/pg-event-server#1]
Due to [this issue](https://github.com/sfackler/rust-postgres/issues/1062), `load_config(None)` now ignores the `PGUSER` env variable and sets `Config::user` to the current OS user instead.

**Comment by dmarteau** [comment]
@ryzhyk Thanks for reporting this !

I updated the dependencies and tests are indeed broken with tokio-postgres v0.7.9.
Working on a workaround...

**Comment by dmarteau** [comment]
They have released v0.7.10 that fix the problem, I will just wait if they are going to yank 0.7.9 before doing anything.

**Comment by dmarteau** [comment]
IMHO a simple warning notice about not using tokio-postgres 1.7.9 should be ok:

* tokio-postgres 1.7.10 is 1.7.9 without the breaking change so 1.7.10 can be used instead without problems.
* I don't  want requiring  1.7.10+ since lower versions are still compatible.

**Comment by dmarteau** [comment]
Tested with 1.7.10 and all is ok.
